name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: pnpm setup
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          package_json_file: frontend/package.json

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Format and Lint
        run: pnpm run check
        working-directory: frontend

      - name: Test
        run: pnpm run test
        working-directory: frontend

      - name: Build
        run: pnpm run build
        working-directory: frontend
